# Generated by Django 5.2.8 on 2025-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedspentmember',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Members part', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sharedspentmember',
            name='is_owner_part',
            field=models.BooleanField(default=False, help_text='Owner part'),
        ),
    ]
